spring:
  data:
    mongodb:
      database: InzApp
      host: localhost
      port: 27017
  security:
    user:
      password: test@1234
      name: noname
  app:
    jwtSecret: Zt6JwL3YV6mR5tKnl9qKmrq1G8tV9lJpHk3FZbWqS0R+KfWkH7LZ0sFwXwWwPj6XqF8C3TtOqEw==
    jwtExpirationMs: 2678400000



server:
  port: 8080

#  ssl:
#    key-store: classpath:balans.p12
#    key-store-password: balans
#    keyStoreType: PKCS12
#    keyAlias: balans
